node_js:
- '0.10'
language: node_js
deploy:
  provider: heroku
  api_key:
    secure: IW3ipEuEnZfvuupOPy9Od0eeJVXQDZmCGCnST5moRdsWkH6U3uSO9nSqeCbaYK7ACAgpc5IeSINldbgsh/Uv8UkM7BWjqbIjG0ybg8+CV38ki6Nc8r9u//MpSWMNQb314pYuk/uhcaTkDN2jp19/DA9Jr8n4/ncSn39yTzlbjz4=
  app: founders-landing
