node_js:
- '0.10'
language: node_js
deploy:
  provider: heroku
  api_key:
    secure: Yyafk2ilfkOok/cJW7mCteZApFTLorfxTV12bNCe7F0VFZKc1PPAT62n98PryUTmnOlpTyDdSQTjgf59uROeZUtY7zjCY3pO4TOClnM1BEuhkSEljqYW44DXPJz5+s8vNXJv9ql/JV6aq+4H2O0iY22ij/bzqlDKHiBgLpCzK0k=
  app: founders-landing
